name: CI/CD

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Install dependencies
      run: composer install
    - name: Run PHP_CodeSniffer
      run: vendor/bin/phpcs

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Install dependencies
      run: composer install
    - name: Set up WordPress
      run: |
        wp core download --allow-root
        cp .env.example .env
        wp config create --dbname=test_db --dbuser=root --dbpass=root --allow-root
        wp db create --allow-root
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

  deploy:
    needs: [lint, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader
    - name: Deploy to Hostinger
      env:
        HOSTINGER_SSH_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
        HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
        HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
        HOSTINGER_PATH: ${{ secrets.HOSTINGER_PATH }}
      run: |
        echo "$HOSTINGER_SSH_KEY" > deploy_key
        chmod 600 deploy_key
        rsync -avz -r -e "ssh -i deploy_key -o StrictHostKeyChecking=no"  --exclude={'.git','.github','wp-content/uploads','phpunit.xml','tests','phpcs.xml','deploy_key','.env'} --update \
          ./ ${HOSTINGER_USER}@${HOSTINGER_HOST}:${HOSTINGER_PATH}
        ssh -i deploy_key -o StrictHostKeyChecking=no ${HOSTINGER_USER}@${HOSTINGER_HOST} \
          "cd ${HOSTINGER_PATH} && \
          wp core update --allow-root && \
          wp plugin update --all --allow-root && \
          wp theme update --all --allow-root"
        rm -f deploy_key