name: Deploy to Hostinger

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: Add Hostinger to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.HOSTINGER_PORT }} -H  ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts
    
      - name: Deploy to Hostinger
        env:
          HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
          HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
          HOSTINGER_PATH: ${{ secrets.HOSTINGER_PATH }}
        run: |
          # Transfer files using rsync
          rsync -avz -e "ssh -p 65002" --update \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.gitignore' \
            --exclude='wp-content/uploads' \
            --exclude='wp-content/themes/coolkidsnetwork/tests' \
            --exclude='wp-content/themes/coolkidsnetwork/vendor' \
            --exclude='phpunit.xml' \
            --exclude='phpcs.xml' \
            --exclude='phpcs.xml.dist' \
            --exclude='.env' \
            $GITHUB_WORKSPACE/ $HOSTINGER_USER@$HOSTINGER_HOST:$HOSTINGER_PATH
          
          # Install theme Composer dependencies
          ssh -p 65002 $HOSTINGER_USER@$HOSTINGER_HOST "cd $HOSTINGER_PATH/wp-content/themes/coolkidsnetwork && composer install --no-dev --optimize-autoloader"
