name: Deploy to Public site

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: 🎉 Deploy

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: SSH setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOSTINGER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy to Hostinger
        run: |
          # Install Composer dependencies
          composer install --no-dev --optimize-autoloader
          
          # Transfer files using rsync (excluding uploads, plugins, and docker-compose.yml)
          rsync -r --update --exclude={'.git','.github','wp-content/uploads','phpunit.xml','wp-content/themes/coolkidsnetwork/tests','phpcs.xml','deploy_key','.env', 'composer.lock', 'composer.json'} --delete-after $GITHUB_WORKSPACE/ ${{ secrets.HOSTINGER_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.HOSTINGER_PATH }}