name: Deploy to Hostinger

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      # - name: Install Composer dependencies
      #   run: composer install --no-dev --optimize-autoloader
    
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: Add Hostinger to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 65002 -H 194.164.74.227 >> ~/.ssh/known_hosts
    
      - name: Deploy to Hostinger
        env:
          HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
          HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
          HOSTINGER_PATH: ${{ secrets.HOSTINGER_PATH }}
        run: |
          rsync -avz -e "ssh -p 65002" --update --exclude={'/.git','/.github','wp-content/uploads','phpunit.xml','wp-content/themes/coolkidsnetwork/tests','/phpcs.xml','/phpcs.xml.dist','deploy_key','/.env', '/composer.lock', '/composer.json', '/vendor'} $GITHUB_WORKSPACE/ $HOSTINGER_USER@$HOSTINGER_HOST:$HOSTINGER_PATH
