name: Lint and test

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Install dependencies
      run: composer install
    - name: Run PHP_CodeSniffer
      run: vendor/bin/phpcs

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Install dependencies
      run: composer install
    - name: Set up WordPress
      run: |
        wp core download --allow-root
        cp .env.example .env
        wp config create --dbname=test_db --dbuser=root --dbpass=root --allow-root
        wp db create --allow-root
    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

  status_checks:
    needs: [lint, test]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Successful PR Check
      run: |
        echo "All checks have passed!"
        exit 0