name: Lint and test

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint:
    name: WPCS check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: VIPCS check
        uses: 10up/wpcs-action@stable
        with:
          standard: 'WordPress'
          extra_args: '--report-json=./phpcs.json'
          use_local_config: 'true'
          only_changed_files: 'true'
          
      - name: Update summary
        run: |
          npm i -g github:10up/phpcs-json-to-md
          phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
          cat phpcs.md >> $GITHUB_STEP_SUMMARY
        if: always()

  status_checks:
    needs: [lint]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Successful PR Check
      run: |
        echo "All checks have passed!"
        exit 0